// Mirrors src/lib/finance.ts's generateStudentId/generateTransactionId so IDs generated by the
// backend look identical to the ones the frontend currently generates client-side.

export function generateStudentId(db) {
  const rows = db.prepare('SELECT id FROM students').all()
  const max = rows.reduce((m, row) => {
    const n = parseInt(row.id.replace('STU-', ''), 10)
    return Number.isFinite(n) ? Math.max(m, n) : m
  }, 0)
  return `STU-${String(max + 1).padStart(3, '0')}`
}

export function generateTransactionId(db, date) {
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const d = String(date.getDate()).padStart(2, '0')
  const prefix = `TRX-${y}${m}${d}-`
  const { count } = db
    .prepare('SELECT COUNT(*) AS count FROM transactions WHERE id LIKE ?')
    .get(`${prefix}%`)
  return `${prefix}${String(count + 1).padStart(4, '0')}`
}
