// Mirrors src/lib/finance.ts's generateStudentId/generateTransactionId so IDs generated by the
// backend look identical to the ones the frontend currently generates client-side.

export function generateStudentId(db) {
  const rows = db.prepare('SELECT id FROM students').all()
  const max = rows.reduce((m, row) => {
    const n = parseInt(row.id.replace('STU-', ''), 10)
    return Number.isFinite(n) ? Math.max(m, n) : m
  }, 0)
  return `STU-${String(max + 1).padStart(3, '0')}`
}

export function generateTransactionId(db, date) {
  var y = date.getFullYear()
  var m = String(date.getMonth() + 1).padStart(2, '0')
  var d = String(date.getDate()).padStart(2, '0')
  var prefix = 'TRX-' + y + m + d + '-'
  var rows = db
    .prepare('SELECT id FROM transactions WHERE id LIKE ?')
    .all(prefix + '%')
  var max = rows.reduce(function (acc, row) {
    var n = parseInt(row.id.replace(prefix, ''), 10)
    return Number.isFinite(n) ? Math.max(acc, n) : acc
  }, 0)
  return prefix + String(max + 1).padStart(4, '0')
}